# Generated by Django 5.1.7 on 2025-03-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_course_created_at_remove_course_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
